# /opt/containers/adguard/compose.yml
services:
  adguard:
    image: adguard/adguardhome:latest
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
