# /opt/containers/caddy/docker-compose.yml
services:
  caddy:
    build: .
    network_mode: host
    privileged: true
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - /mnt/peach_storage/signal-decoded:/mnt/peach_storage/signal-decoded:ro
volumes:
  caddy_data:
