version: "3.8"

services:
  finance-scraper:
    build: .
    container_name: finance-scraper
    privileged: true
    restart: "no"
    volumes:
      - /opt/textfiles:/opt/textfiles
      - ./state:/state
    env_file: .env

  finance-receiver:
    build: ./receiver
    container_name: finance-receiver
    restart: unless-stopped
    ports:
      - "9107:9107"
    volumes:
      - /opt/textfiles:/opt/textfiles
    env_file: .env
